name: Update README

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch GitHub followers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s https://api.github.com/users/samarjitsahoo \
            | jq '.followers' > followers.txt

      - name: Update README
        run: |
          followers=$(cat followers.txt)
          sed -i "s/<!-- followers -->/${followers}/g" README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update follower count"
          git push
